---
- hosts: all
  become: yes
  vars:
    storm:
      version: 1.1.1
      mirror: http://www-us.apache.org/dist
      user: storm
      group: root
      install_dir: /opt
      base_dir: /opt/storm
      log_dir: /opt/storm-log
  tasks:

  - name: User | Create Group
    become_user: root
    group:
      name: "{{storm.group}}"
      state: present

  - name: User | Create User
    become_user: root
    user:
      name: "{{storm.user}}"
      group: "{{storm.group}}"
      state: present

  - name: Install add-apt-repostory
    become: yes
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default

  - name: Nimbus | Download Storm
    get_url:
      url: http://www-us.apache.org/dist/storm/apache-storm-{{storm.version}}/apache-storm-{{storm.version}}.tar.gz
      dest: /tmp/apache-storm-{{storm.version}}.tar.gz

  - name: Nimbus | Extract Storm
    become_user: root
    command: tar xzf /tmp/apache-storm-{{storm.version}}.tar.gz chdir="{{storm.install_dir}}"

  - name: Nimbus | Update permissions
    become_user: root
    file:
      path: "{{ storm.install_dir }}"
      owner: "{{ storm.user }}"
      group: "{{ storm.group }}"
      recurse: yes
      mode: 0755
      state: directory

  - name: Nimbus | Create base directory
    become_user: root
    file:
      path: "{{storm.base_dir}}"
      owner: "{{storm.user}}"
      group: "{{storm.group}}"
      mode: 0777
      state: directory

  - name: Nimbus | Create log directory
    become_user: root
    file:
      path: "{{storm.log_dir}}"
      owner: "{{storm.user}}"
      group: "{{storm.group}}"
      mode: 0777
      state: directory

  - name: Nimbus | Update base permissions
    become_user: root
    file:
      path: "{{ storm.base_dir }}"
      owner: "{{ storm.user }}"
      group: "{{ storm.group }}"
      recurse: yes
      mode: 0777
      state: directory

  - name: Nimbus | Update log permissions
    become_user: root
    file:
      path: "{{ storm.log_dir }}"
      owner: "{{ storm.user }}"
      group: "{{ storm.group }}"
      recurse: yes
      mode: 0777
      state: directory

  - name: Nimbus | Set config
    template:
      src: "templates/nimbus/storm.yaml"
      dest: "{{storm.install_dir}}/apache-storm-{{ storm.version }}/conf/"

#  - name: Nimbus | Set init.d environment
#    template:
#      src: "templates/nimbus/nimbus"
#      dest: "/etc/init.d/"
#      mode: 0755

#  - name: Nimbus | Configure autostart
#    file:
#      src: /etc/init.d/nimbus
#      dest: /etc/rc2.d/S99nimbus
#      state: link

#  - name: Nimbus | Run service
#    service: name=nimbus state=started enabled=yes
#  - name: Nimbus | Run service
#    shell: "{{storm.install_dir}}/apache-storm-{{storm.version}}/bin/storm nimbus &"

